project:
  type: website
  output-dir: docs

website:
  title: "Diário de Ecologia de Paisagens"
  navbar:
    left:
      - text: Início
        href: index.qmd
      - text: Aula 1
        href: aula1.qmd
      - text: Sobre mim
        href: about.qmd
    page-footer: 
    center: "© 2026 • Joyce Beatriz • Ecologia de Paisagens"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: right
    
