<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exercícios – Diário de Ecologia de Paisagens</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Diário de Ecologia de Paisagens</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Início</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./aula1.html"> 
<span class="menu-text">Aulas</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">Sobre mim</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Exercícios.html" aria-current="page"> 
<span class="menu-text">Exercícios</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#exercício-1-o-mosaico-no-lance-de-vista" id="toc-exercício-1-o-mosaico-no-lance-de-vista" class="nav-link active" data-scroll-target="#exercício-1-o-mosaico-no-lance-de-vista">Exercício 1: O Mosaico no Lance de Vista</a></li>
  <li><a href="#exercício-2-workbook-de-ecologia-de-paisagens" id="toc-exercício-2-workbook-de-ecologia-de-paisagens" class="nav-link" data-scroll-target="#exercício-2-workbook-de-ecologia-de-paisagens">Exercício 2: Workbook de Ecologia de Paisagens</a></li>
  <li><a href="#apresentação-do-workbook" id="toc-apresentação-do-workbook" class="nav-link" data-scroll-target="#apresentação-do-workbook">🎬 Apresentação do Workbook</a></li>
  <li><a href="#exercício-3-pacotes-r-para-ecologia-de-paisagens" id="toc-exercício-3-pacotes-r-para-ecologia-de-paisagens" class="nav-link" data-scroll-target="#exercício-3-pacotes-r-para-ecologia-de-paisagens">Exercício 3: Pacotes R para Ecologia de Paisagens</a></li>
  <li><a href="#exercício-4-amostragem-de-paisagens-com-restrição-de-borda-murici-al" id="toc-exercício-4-amostragem-de-paisagens-com-restrição-de-borda-murici-al" class="nav-link" data-scroll-target="#exercício-4-amostragem-de-paisagens-com-restrição-de-borda-murici-al">Exercício 4: Amostragem de Paisagens com Restrição de Borda — Murici-AL</a></li>
  <li><a href="#exercício-4.1---aplicando-em-outras-paisagens-cabaceiras-pb" id="toc-exercício-4.1---aplicando-em-outras-paisagens-cabaceiras-pb" class="nav-link" data-scroll-target="#exercício-4.1---aplicando-em-outras-paisagens-cabaceiras-pb">Exercício 4.1 - Aplicando em outras paisagens CABACEIRAS-PB</a></li>
  <li><a href="#exercício-5-exercício-prático-consultoria-técnica-para-criação-de-unidades-de-conservação-ucs" id="toc-exercício-5-exercício-prático-consultoria-técnica-para-criação-de-unidades-de-conservação-ucs" class="nav-link" data-scroll-target="#exercício-5-exercício-prático-consultoria-técnica-para-criação-de-unidades-de-conservação-ucs">Exercício 5: Exercício Prático: Consultoria Técnica para Criação de Unidades de Conservação (UCs)</a></li>
  <li><a href="#por-dentro-do-exercicio-5-script-e-comentários" id="toc-por-dentro-do-exercicio-5-script-e-comentários" class="nav-link" data-scroll-target="#por-dentro-do-exercicio-5-script-e-comentários">Por dentro do Exercicio 5: script e comentários</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exercícios</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="exercício-1-o-mosaico-no-lance-de-vista" class="level2">
<h2 class="anchored" data-anchor-id="exercício-1-o-mosaico-no-lance-de-vista">Exercício 1: O Mosaico no Lance de Vista</h2>
<p><strong>Parte 1: Delimitação e Descrição (A Paisagem Humana)</strong></p>
<p><img src="images\exercicio1.jpeg" class="img-fluid" alt="São josé dos cordeiros - PB"> Matriz: vegetação de caatinga Manchas: Açude, solo exposto (áreas de cultivo/pastagem), afloramento rochoso Corredores: estrada de terra Grão: Casa como menor elemento</p>
<p><strong>Parte 2: Escala, Granulação e Transmutação</strong></p>
<p><img src="images\exercicio2.jpeg" class="img-fluid" alt="Parte de cima quadrante escolhido; Parte de baixo mostrando a homogeinização do quadrante"> Grão: Casa como menor elemento</p>
<p><strong>Parte 3: A “Lente Biológica” (Escala de Percepção)</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\exercicio3.jpeg" class="img-fluid figure-img"></p>
<figcaption>Moita na percepção de um garfanhoto</figcaption>
</figure>
</div>
<p>A moita de capim para o garfanhoto é percebida como um ambiente heterogêneo e complexo, onde na área observada tem vários habitats como folhas, troncos e outros animais, que vão ser importantes para a sobrevivência dele ou alimento e abrigo.</p>
<p><strong>Questões para Discussão</strong></p>
<ol type="1">
<li><strong>Ao aumentar o tamanho do grão (Parte 2), você perdeu informações que seriam vitais para a conservação de alguma espécie específica?</strong></li>
</ol>
<p>R- Sim, Ao aumentar o tamanho do grão, alguns detalhes da paisagem foram “perdidos”, como exemplo a estrada que corta as áreas e age como um corredor. Essa “perda” do elemento, poderia nos enganar em achar que não existiria esse corredor e fazer imaginar que é somente uma área homogenea.</p>
<ol start="2" type="1">
<li><strong>Como a conectividade funcional mudou entre a sua visão humana e a visão do “gafanhoto”? Elementos que eram barreiras continuam sendo?</strong></li>
</ol>
<p>R-O que antes para mim era uma grande área de vegetação com corredores e manchas, para o garfanhoto não é algo que existe, visto que a área em que ele habita a paisagem é diferente da minha e os elementos presentes também.</p>
<ol start="3" type="1">
<li><strong>Você consegue identificar algum distúrbio (natural ou antrópico) que foi o responsável por criar essa heterogeneidade que você desenhou?</strong></li>
</ol>
<p>R- Sim, há indícios de distúrbios, como a estrada de terra para o acesso de pessoas para as áreas, as áreas mais abertas sugerindo que há uso do solo para agricultura ou pastagem.</p>
</section>
<section id="exercício-2-workbook-de-ecologia-de-paisagens" class="level2">
<h2 class="anchored" data-anchor-id="exercício-2-workbook-de-ecologia-de-paisagens">Exercício 2: Workbook de Ecologia de Paisagens</h2>
</section>
<section id="apresentação-do-workbook" class="level2">
<h2 class="anchored" data-anchor-id="apresentação-do-workbook">🎬 Apresentação do Workbook</h2>
<div class="quarto-video ratio ratio-16x9"><iframe data-external="1" src="https://www.youtube.com/embed/ZWoAbrqc0hU" title="" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe></div>
</section>
<section id="exercício-3-pacotes-r-para-ecologia-de-paisagens" class="level2">
<h2 class="anchored" data-anchor-id="exercício-3-pacotes-r-para-ecologia-de-paisagens">Exercício 3: Pacotes R para Ecologia de Paisagens</h2>
<p><strong>4 Conhecendo os pacotes principais</strong></p>
<p><strong>4.1 terra — Dados Raster</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\e3i1.png" class="img-fluid figure-img"></p>
<figcaption>Paisagem simulada - Uso do solo</figcaption>
</figure>
</div>
<p><strong>4.1.1 Operações básicas com rasters</strong></p>
<pre><code>class       : SpatRaster 
size        : 50, 50, 1  (nrow, ncol, nlyr)
resolution  : 1, 1  (x, y)
extent      : 0, 50, 0, 50  (xmin, xmax, ymin, ymax)
coord. ref. : lon/lat WGS 84 (CRS84) (OGC:CRS84) 
source(s)   : memory
categories  : label 
name        :    label 
min value   : Floresta 
max value   :     Água 
 res(r)            # Resolução espacial
[1] 1 1
 ext(r)            # Extensão geográfica
SpatExtent : 0, 50, 0, 50 (xmin, xmax, ymin, ymax)
 ncell(r)          # Número total de células
[1] 2500
 freq(r)           # Frequência de cada classe (tabela de área)
  layer       value count
1     1    Floresta  1257
2     1    Pastagem   490
3     1 Agricultura   482
4     1        Água   271</code></pre>
<p><strong>4.2 sf — Dados Vetoriais</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\e3i2.png" class="img-fluid figure-img"></p>
<figcaption>Parcelas sobre o mapa de uso do solo</figcaption>
</figure>
</div>
<p><strong>4.3 landscapemetrics — Métricas de Paisagem</strong></p>
<p><img src="images\e3i3.png" class="img-fluid"></p>
<p><strong>4.3.1 Calculando múltiplas métricas de uma vez</strong></p>
<p><strong>4.3.2 Visualizando fragmentos</strong></p>
<p><img src="images\e3i4.png" class="img-fluid"></p>
<p><img src="images\e3i5.png" class="img-fluid"></p>
<p><strong>4.4 tmap — Mapas Temáticos</strong></p>
<p><img src="images\e3i6.png" class="img-fluid"> <img src="images\e3i7.png" class="img-fluid"></p>
<p><strong>4.5 vegan — Ecologia de Comunidades</strong></p>
<p><img src="images\e3i8.png" class="img-fluid"></p>
<p><strong>5 Fluxo de trabalho integrado</strong></p>
<p>class id area isolamento perimetro_area <int> <int> <dbl> <dbl> <dbl> 1 1 1 0.0001 7 4<br>
2 1 2 0.0005 4 2.4<br>
3 1 3 0.0072 2 0.833 4 1 4 0.0001 6.32 4<br>
5 1 5 0.0001 5 4<br>
6 1 6 0.008 2.24 0.85</dbl></dbl></dbl></int></int></p>
<p><img src="images\e3i9.png" class="img-fluid"></p>
</section>
<section id="exercício-4-amostragem-de-paisagens-com-restrição-de-borda-murici-al" class="level2">
<h2 class="anchored" data-anchor-id="exercício-4-amostragem-de-paisagens-com-restrição-de-borda-murici-al">Exercício 4: Amostragem de Paisagens com Restrição de Borda — Murici-AL</h2>
<p><strong>Contexto do exercício</strong></p>
<p>Neste exercício você trabalhará com um mapa de uso e cobertura da terra do município de Murici (AL), obtido por classificação de imagens de satélite. O objetivo é selecionar 15 pontos amostrais no interior de remanescentes florestais que estejam a pelo menos 2 km da borda do mapa (para evitar efeitos de borda não controlados). Em cada ponto será extraído um buffer circular de 500 m de raio e calculada a composição percentual de cada classe de uso do solo.</p>
<p>Adicionalmente, usaremos o pacote landscapemetrics para calcular métricas de diversidade (Shannon), proporção de floresta e densidade de borda para cada uma das 15 paisagens amostrais.</p>
<p><strong>Objetivos específicos</strong></p>
<p>-Compreender a importância da projeção cartográfica para análises métricas. -Aplicar buffer negativo para restrição de borda de mapa. -Realizar amostragem aleatória com distância mínima entre pontos. -Extrair e quantificar a composição da paisagem em buffers circulares. -Calcular métricas de paisagem com landscapemetrics. -Produzir um painel de visualização das paisagens amostrais.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\Área de sorteio MURICI.png" class="img-fluid figure-img"></p>
<figcaption>Visualização da área de sorteio</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\pontos amostrais e buffers de 500 MURICI.png" class="img-fluid figure-img"></p>
<figcaption>visualização dos Pontos amostrais e buffers de 500m</figcaption>
</figure>
</div>
<p><strong>Análise com landscapemetrics:</strong></p>
<p>Diversidade da paisagem – Índice de Shannon % de cobertura florestal – Proporção da classe “Formação Florestal” Densidade de borda da classe floresta</p>
<pre><code>id_buffer diversidade_shannon perc_floresta densidade_borda_m_ha
1          1           0.7507504      78.22410             44.41351
2          2           0.7551841      75.62028             53.66340
3          3           1.2318169      49.41922             53.94980
4          4           0.8906418      71.73679             33.35833
5          5           1.0747283      57.00326             63.86672
6          6           0.0000000     100.00000              0.00000
7          7           1.3336246      31.62939             74.45502
8          8           0.8789672      70.95745             25.38790
9          9           1.3141271      23.73247             48.22454
10        10           0.7153538      69.32907             24.34106
11        11           1.0003162      44.07684             58.11278
12        12           1.2808703      13.84452             44.74460
13        13           0.6093134      83.75527             24.81909
14        14           0.0000000     100.00000              0.00000
15        15           1.0722640      23.58591             53.09069</code></pre>
<p><strong>Interpretação dos resultados</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images\painel de amostragem MURICI.png" class="img-fluid figure-img"></p>
<figcaption>Painel de amostragem - MURICI</figcaption>
</figure>
</div>
</section>
<section id="exercício-4.1---aplicando-em-outras-paisagens-cabaceiras-pb" class="level2">
<h2 class="anchored" data-anchor-id="exercício-4.1---aplicando-em-outras-paisagens-cabaceiras-pb">Exercício 4.1 - Aplicando em outras paisagens CABACEIRAS-PB</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/area sorteio CABACEIRAS.png" class="img-fluid figure-img"></p>
<figcaption>área de sorteio CABACEIRAS PB</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pontos amostrais e buffers CABACEIRAS.png" class="img-fluid figure-img"></p>
<figcaption>Pontos amostrais e buffers CABACEIRAS PB</figcaption>
</figure>
</div>
<p><strong>Analise com landscapemetrics</strong></p>
<pre><code>id_buffer diversidade_shannon perc_floresta densidade_borda_m_ha
1         1           0.8940560     9.6153846            25.802457
2         2           0.8111290     2.6737968            15.785032
3         3           1.1411803     3.8054968            23.402228
4         4           0.6002437     3.9487727            19.331190
5         5           1.3292682     4.6038544            18.675012
6         6           1.1492410     1.0582011            12.068451
7         7           1.2258667     1.3888889             7.167349
8         8           1.1166426     0.5291005             3.549544</code></pre>
<p><strong>Interpretação dos resultados</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/painel de amostragem CABACEIRAS.png" class="img-fluid figure-img"></p>
<figcaption>Painel de amostragem CABACEIRAS PB</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Algumas partes do script foram alteradas visando se encaixar ao mapa de cabaceiras</p>
</div>
</div>
<p>O erro ocorreu porque o número de rótulos (labels) não correspondia ao número de feições (pontos) no objeto espacial.</p>
<pre><code>geom_spatvector_text(aes(label = 1:15))</code></pre>
<p>O código original usa 15 rótulos fixos, mas o número real de pontos era diferente (8), e o ggplot exige que o número de labels seja igual ao número de feições. Então corrigi, com auxilio de inteligencia artificial, criando um identificador (ID) nos pontos:</p>
<pre><code>pontos_finais$ID &lt;- 1:nrow(pontos_finais)</code></pre>
<p>Com isso, foi criado um ID automático e foi garantido que o número de labels é igual ao número de pontos. Depois foi corrigido o “geom_spatvector_text”, para que cada ponto receba seu próprio rótulo e que não tenha conflito de tamanho</p>
<pre><code>geom_spatvector_text(
  data = pontos_finais, 
  aes(label = ID), 
  color = "white", 
  size = 3, 
  vjust = -0.8
)</code></pre>
</section>
<section id="exercício-5-exercício-prático-consultoria-técnica-para-criação-de-unidades-de-conservação-ucs" class="level2">
<h2 class="anchored" data-anchor-id="exercício-5-exercício-prático-consultoria-técnica-para-criação-de-unidades-de-conservação-ucs">Exercício 5: Exercício Prático: Consultoria Técnica para Criação de Unidades de Conservação (UCs)</h2>
<p>• O objetivo da consultoria é fundamentar tecnicamente a criação de novas Unidades de Conservação, identificando áreas que possuam características espaciais favoráveis à manutenção da biodiversidade e à integridade dos processos ecológicos. Objetivos do Exercício</p>
<ol type="1">
<li>Quantificar a estrutura da paisagem utilizando o modelo Mancha-Corredor-Matriz.</li>
<li>Analisar a composição e a configuração espacial de fragmentos florestais.</li>
<li>Propor áreas prioritárias para conservação com base em métricas de paisagem.</li>
</ol>
<p><strong>Introdução</strong></p>
<p>A área de escolha para a realização da instalação da unidade de conservação consiste no município de Cabaceiras localizado no estado da Paraíba e inserido na Mesorregião da Borborema. A região possui uma área aproximada de 400,22 km² e população estimada em 5.336 habitantes. O município está nos domínios da bacia hidrográfica do Rio Paraíba e é drenado pelos rios Taperoá, Paraíba e Boa Vista. A vegetação predominante é a Caatinga arbustiva, típica das regiões semiáridas do Nordeste brasileiro, mas ainda apresentando manchas de floresta densa. Diante disso, Cabaceiras pode funcionar como uma área representativa da Caatinga e está inserida na região do Cariri Paraibano. O Cariri Paraibano é uma sub-região da Caatinga localizada no estado da Paraíba, no Nordeste do Brasil. Ela possui uma área de 11.233,5 km² e é composta por 29 municípios. Até o final do século XVIII, o Cariri Paraibano era composto por paisagens de bosques e florestas ribeirinhas, que foram substituídas por áreas de pecuária e plantio de algodão. Contudo, as atividades agrícolas de algodão declinaram a partir dos anos 1950, deixando áreas severamente degradadas. Atualmente, a região é um mosaico de uso do solo e degradação da vegetação originária, com algumas áreas florestais ainda preservadas (Souza, 2009, 2016). A Caatinga é considerada a maior floresta sazonalmente seca do mundo, abriga inúmeras espécies endêmicas e possui grande relevância ecológica, social e cultural. Apesar disso, a conservação desse bioma recebe pouca prioridade, refletido na baixa quantidade de áreas protegidas existentes. Atualmente, apenas cerca de 8,9% da área da Caatinga encontra-se protegida por Unidades de Conservação (UCs), sendo a maior parte representada por Áreas de Proteção Ambiental (APAs), categoria considerada menos restritiva. Esse cenário evidencia a necessidade de criação e ampliação de novas Unidades de Conservação na Caatinga, especialmente em regiões suscetíveis à degradação ambiental, como o Cariri Paraibano.</p>
<p><strong>Descrição da metodologia de amostragem</strong></p>
<p><strong>Procedimentos Técnicos</strong></p>
<p><strong>1. Obtenção e Preparo dos Dados</strong></p>
<p>Foi selecionado o município brasileiro (Cabaceiras – PB) e foi realizado o download do mapa de uso e cobertura da terra mais recente da plataforma MapBiomas (2024). Foi utilizado o programa Rstudio para a realização dos processamewntos dos dados raster .</p>
<p><strong>2. Delineamento Amostral: Pontos-Paisagem e Quantificação da Estrutura (Métricas de Paisagem)</strong></p>
<p>O processamento dos dados espaciais foi realizado no Rstudio. De inicio foi garantido que o sistema de coordenadas estivesse projetado corretamente para a região de Cabaceiras (fuso UTM 24 Sul, EPSG: 31984). Em seguida, foi feito um sorteio de pontos amostrais de forma aleatória, restritos espacialmente à classe de uso definida como “Floresta”. Ao redor de cada ponto sorteado, foi estabelecido um buffer de 500 metros de raio. Porem, para assegurar a independência das amostras, foi definida uma distância mínima de 1.000 metros entre os pontos, para garantir que os buffers não se tocassem ou se sobrepusessem. A organização dos mapas, o ajuste de coordenadas, o recorte da área de estudo e a criação das zonas de amortecimento, foi feita com o auxílio do pacote terra. Já para compreender a saúde ecológica dessas manchas florestais e conseguir quantificar a estrutura espacial, foram calculadas métricas de ecologia de paisagem utilizando o pacote landscapemetrics. As medidas foram realizadas nos níveis de mancha, classe e paisagem, extraindo dados como área, perímetro, área central, índice de forma, isolamento, percentual de floresta, densidade da borda e a diversidade de Shannon dentro de cada buffer. Por fim, o tratamento e a estruturação tabular dos resultados foram organizados com o pacote tidyverse, enquanto a elaboração dos mapas e das representações visuais foi feita utilizando o pacote ggplot2 com a extensão tidyterra.</p>
<p><strong>Resultados</strong></p>
<p>A análise do mapa de uso e cobertura do solo nos mostra que a paisagem é dominada pela classe de Formação Savânica e por áreas de uso humano representadas principalmente por Pastagem e Mosaico de Usos. As Formações Florestais apresentam uma distribuição bastante restrita e fragmentada, formando pequenas manchas isoladas dentro da matriz. Já outras classes, como Corpos d’Água e Áreas Urbanizadas, ocorrem em pequenas proporções e de forma pontual pelo território.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/mapa_uso_cabaceiras.png" class="img-fluid figure-img"></p>
<figcaption>Mapa de uso e cobertura do solo de Cabaceiras PB</figcaption>
</figure>
</div>
<p>Após as analises foram sorteados 15 pontos ao longo do território de cabaceiras visando analisar qual desses pontos de floresta melhor serviriam para a implementação da unidade de conservação. A distribuição dos pontos acompanhou a ocorrência natural da formação florestal e se concentraram no centro-sul e nordeste do mapa. Para evitar erros, os pontos que cairam muito na borda foram ignorados, para evitar erros e problemas causados por efeitos de borda não controlados fora da área mapeada. A única exceção foi a paisagem referente ao ponto 5 na parte sul, que foi mantida na amostragem por apresentar potencial estratégico para a futura criação da unidade de conservação.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/pontos_cabaceiras.png" class="img-fluid figure-img"></p>
<figcaption>Pontos de floresta sorteados</figcaption>
</figure>
</div>
<p><strong>1.1 Quantificação da Estrutura (Métricas de paisagem e mancha)</strong></p>
<p>A análise das métricas espaciais para os 15 buffers mostrou variações significativas entre os buffers. Em termos de representatividade da formação florestal, o Buffer 5 se destaca como o melhor cenário, pois possui maior proporção de cobertura florestal (18,26%) e também demonstra alta heterogeneidade na paisagem (Índice de Shannon de 1,34). Porém, ela possui a maior densidade de borda do conjunto (48,08 m/ha), o que pode nos dizer que mesmo tendo uma boa quantidade de floresta, a mancha tem formatos irregulares ou pode estar fragmentada na matriz. O Buffer 4 também demonstrou resultados positivos, sendo a segunda área com maior percentual florestal (11,76%), apresentando um índice de shannon de 0,98 e densidade de borda de 36,20, números menores que o buffer 5, mas que ainda a colocam como possível área. Em contrapartida, os piores cenários foram vistos nos Buffers 3 e 13, ambos possuindo cerca de 0,5% de floresta em sua composição, os tornando inviáveis para áreas prioritárias. Em relação à composição da paisagem, o Buffer 2 foi o que apresentou a maior diversidade de classes (Índice de Shannon de 1,44), indicando uma paisagem bem heterogênea. Já os Buffers 15 e 10 obtiveram os menores valores de diversidade (Shannon de 0,08 e 0,17, respectivamente).</p>
<pre><code> 
&gt; print(metricas_paisagem)
   id_buffer diversidade_shannon perc_floresta densidade_borda_m_ha
1          1          1.23057611     3.6286019            22.206778
2          2          1.43889928     6.7235859            37.608253
3          3          1.28042224     0.5393743             3.620376
4          4          0.98333430    11.7583603            36.203763
5          5          1.33698655    18.2584270            48.078801
6          6          1.32890281     3.8379531            23.614271
7          7          1.25104207     1.3874066             7.163477
8          8          0.79134328     2.6539278            15.675999
9          9          0.62975187     4.0000000            19.592302
10        10          0.17227395     1.0245902            11.003570
11        11          1.12990123     2.1668472             7.272132
12        12          0.75669105     2.1164021             6.510931
13        13          1.11726105     0.5319149             3.570307
14        14          1.13870407     1.0660981            12.164928
15        15          0.08304324     1.6245487            10.904260
</code></pre>
<p>A avaliação no nível da mancha nos deu um bom detalhamento sobre a qualidade e a viabilidade dos fragmentos florestais presentes. O Buffer 4 registou a maior área média de mancha (4,84 ha) e a maior core area (2,18 ha). O Buffer 5 também tem potencial, pois além de apresentar uma boa core area (1,19 ha), as suas manchas possuem índices de forma e dimensão fractal mais próximos de 1 (1,43 e 1,06, respetivamente). Já os Buffers 3, 10, 13, 14 e 15 configuram os piores cenários estruturais. Nestas áreas, as manchas florestais possuem médias inferiores a 0,5 ha e apresentam um valor de core area igual a zero. O Buffer 10 demonstrou ser altamente isolado, apresentando a maior distância para o vizinho mais próximo (enn de 364 m). Diversos buffers (3, 7, 8, 9, 11, 12 e 13) são uma única mancha florestal isolada dentro da zona de amortecimento.</p>
<pre><code> plot_id  area   core   enn  frac perim shape
     
 1       1 1.51  0.0888 107.   1.12  924.  1.83
 2       2 1.40  0.244  143.   1.10  790.  1.68
 3       3 0.444 0      NaN    1.03  298.  1.12
 4       4 4.84  2.18   246.   1.11 1520.  1.81
 5       5 2.31  1.19   115.   1.06  751.  1.43
 6       6 1.60  0.178   89.4  1.14  983.  1.94
 7       7 1.15  0.178  NaN    1.07  596.  1.39
 8       8 2.22  0.0888 NaN    1.16 1311.  2.20
 9       9 3.28  0.977  NaN    1.15 1609.  2.22
10      10 0.222 0      364.   1.07  268.  1.38
11      11 1.78  0.533  NaN    1.02  596.  1.12
12      12 1.07  0.0888 NaN    1.08  596.  1.44
13      13 0.444 0      NaN    1.03  298.  1.12
14      14 0.444 0      233.   1.14  507.  1.86
15      15 0.400 0      215.   1.04  298.  1.19</code></pre>
<p>A representação cartográfica dos 15 recortes circulares (Painel de Amostragem) corrobora visualmente com os dados quantitativos obtidos pelas métricas.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/painel_cabaceiras.png" class="img-fluid figure-img"></p>
<figcaption>Painel de amostragem das áreas sorteadas</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Algumas imagens estão cortadas pois elas se localizam na borda do mapa</p>
</div>
</div>
<p>A Paisagem 4 possui uma mancha florestal contínua e mais centralizada, imersa em grande parte em uma matriz de formação savânica e de mosaico de usos. Justificando o valor de core area, o que pode indicar um fragmento mais protegido das pressões externas. Já a Paisagem 5 se destaca por uma extensa faixa florestal localizada na borda do limite do mapa e diretamente contígua a um corpo d’água. Isto lhe da confere um valor ecológico, pois pode sugerir a presença de uma mata ciliar ou uma vegetação associada a recursos hídricos. Porem, é possível ver que essa mesma floresta está cercada por área de pastagem, o que explicaria o valor da densidade de borda, indicando uma área de alta pressão antrópica e vulnerabilidade ao efeito de borda.</p>
<p><img src="images/paisagem4.png" class="img-fluid" alt="Detalhe da paisagem 4"> <img src="images/paisagem5.png" class="img-fluid" alt="Detalhe da paisagem 5"></p>
<p><strong>4. Interpretação e Proposta de Manejo</strong></p>
<p><strong>• Quais pontos-paisagem apresentam a melhor integridade ecológica?</strong></p>
<p>Os Buffers 4 e 5.</p>
<p><strong>• Existem áreas que funcionam como trampolins ecológicos (stepping stones) ou que facilitam a conectividade funcional?</strong></p>
<p>Sim. A análise da métrica de isolamento mostra que áreas como os Buffers 6 (89,4 m), 1 (107 m) e 5 (115 m) possuem manchas florestais relativamente próximas umas das outras. Esses fragmentos menores podem então atuar como stepping stones dentro da matriz dominante de formação savânica e pastagem. Eles podem ser fundamentais para facilitar a conectividade funcional, pois acaba reduzindo a distância de voo ou deslocamento da fauna, o que permite fluxo gênico e dispersão de sementes entre manchas maiores que estariam isoladas.</p>
<p><strong>• Onde o governo deve instalar a nova UC? Justifique com base em conceitos como o limiar crítico de habitat (ex: regra dos 30%) e a viabilidade populacional das manchas.</strong></p>
<p>O governo deve instalar a nova UC na área correspondente ao Buffer 5. Nenhuma das paisagens amostradas atinge o valor mínimo ideal do limiar crítico ( Buffer 5 é o que chega mais perto, com 18,26%). Por estar abaixo do limiar crítico, a escolha do Buffer 5 é fundamental, pois ele possui a maior base florestal para iniciar um processo de recuperação e já conta com uma área central viável (1,19 ha) para sustentar populações remanescentes, além de proteger um corpo d’água. Diante desse cenário de fragmentação, a criação da UC não deve seguir um modelo de proteção estrita (fechada/cercada). A recomendação é a criação de uma Unidade de Conservação de Uso Sustentável, integrando a comunidade local. Dessa forma, é possível utilizar técnicas de agricultura sustentável (como sistemas agroflorestais) integradas à restauração ecológica das pastagens de entorno. Isso permitirá que, a médio e longo prazo, a cobertura florestal local se expanda, ultrapassando o limiar de 30% e garantindo a resiliência ecológica da paisagem sem excluir as pessoas que ali vivem.</p>
<p><strong>Parecer Técnico Resumido: Indicação clara de qual área deve ser protegida e por quais razões ecológicas espaciais.</strong></p>
<p>A área escolhida foi a 5, pois a mesma se destaca por ter a maior proporção de cobertura florestal entre todas as áreas amostradas (18,26%) e por manter uma core area viável (1,19 ha) para o refúgio da biodiversidade. O fator ecológico de maior relevância é a associação desse remanescente florestal com um corpo d’água, sugerindo a possível presença de mata ciliar. A proteção dessa área vai poder garantir a conservação da flora e fauna nativa e também a manutenção dos recursos hídricos, um serviço ecossistêmico crítico na região da Caatinga. Embora as métricas apontem uma elevada densidade de borda (48,08 m/ha) devido a pressão das áreas de pastagem e do mosaico de usos do entorno, essa vulnerabilidade justifica necessidade de intervenção. Porém, ao invés de adotar um modelo de conservação que visa o isolamento da área, a heterogeneidade e a ocupação antrópica dessa paisagem oferecem o cenário ideal para a criação de uma Unidade de Conservação de Uso Sustentável. Tendo em mente que presença de moradores e atividades agrícolas não deve ser vista como um impeditivo, mas como uma oportunidade para aplicar métodos de integração sustentável, como sistemas agroflorestais e técnicas de agricultura aliadas à restauração ecológica das bordas da floresta.</p>
</section>
<section id="por-dentro-do-exercicio-5-script-e-comentários" class="level2">
<h2 class="anchored" data-anchor-id="por-dentro-do-exercicio-5-script-e-comentários">Por dentro do Exercicio 5: script e comentários</h2>
<p><strong>TENTATIVA CABACEIRAS ————————————-</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'terra' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>terra 1.9.11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'tidyverse' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'ggplot2' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'tibble' foi compilado no R versão 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'tidyr' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'readr' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'purrr' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'dplyr' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'stringr' foi compilado no R versão 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'forcats' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'lubridate' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1     </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::extract() masks terra::extract()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyterra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'tidyterra' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Anexando pacote: 'tidyterra'

O seguinte objeto é mascarado por 'package:stats':

    filter</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(landscapemetrics)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: pacote 'landscapemetrics' foi compilado no R versão 4.5.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>r_cabaceiras <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"2024_cabaceiras.tif"</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>r_utm <span class="ot">&lt;-</span> <span class="fu">project</span>(r_cabaceiras, <span class="st">"EPSG:31984"</span>, <span class="at">method =</span> <span class="st">"near"</span>)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Projeção e legenda</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>legenda <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">id =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">11</span>, <span class="dv">15</span>, <span class="dv">20</span>, <span class="dv">21</span>, <span class="dv">24</span>, <span class="dv">25</span>, <span class="dv">33</span>),</span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Categoria =</span> <span class="fu">c</span>(<span class="st">"Formação Florestal"</span>, <span class="st">"Formação Savânica"</span>, <span class="st">"Campo Alagado"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Pastagem"</span>, <span class="st">"Cana"</span>, <span class="st">"Mosaico de Usos"</span>, <span class="st">"Área Urbanizada"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>                <span class="st">"Outras Áreas não Vegetadas"</span>, <span class="st">"Corpo d'Água"</span>),</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">Cores =</span> <span class="fu">c</span>(<span class="st">"#006400"</span>, <span class="st">"#7cfc00"</span>, <span class="st">"#00ffff"</span>, <span class="st">"#ffff00"</span>, <span class="st">"#ff4500"</span>,</span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>            <span class="st">"#f4a460"</span>, <span class="st">"#ff0000"</span>, <span class="st">"#d3d3d3"</span>, <span class="st">"#0000ff"</span>)</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(r_utm) <span class="ot">&lt;-</span> legenda[,<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a><span class="co"># definindo a área de sorteio (SEM restrição de borda)</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>vetor_total <span class="ot">&lt;-</span> <span class="fu">as.polygons</span>(r_utm, <span class="at">dissolve =</span> <span class="cn">TRUE</span>)</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a><span class="co"># limite do município</span></span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>municipio_limite <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(vetor_total)</span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a><span class="co"># selecionar apenas floresta</span></span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>floresta <span class="ot">&lt;-</span> vetor_total[vetor_total<span class="sc">$</span>Categoria <span class="sc">==</span> <span class="st">"Formação Florestal"</span>, ]</span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a><span class="co"># área de sorteio = floresta inteira dentro do município</span></span>
<span id="cb30-30"><a href="#cb30-30" aria-hidden="true" tabindex="-1"></a>area_sorteio <span class="ot">&lt;-</span> <span class="fu">mask</span>(floresta, municipio_limite)</span>
<span id="cb30-31"><a href="#cb30-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-32"><a href="#cb30-32" aria-hidden="true" tabindex="-1"></a><span class="co"># um único objeto</span></span>
<span id="cb30-33"><a href="#cb30-33" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">is.list</span>(area_sorteio)) {</span>
<span id="cb30-34"><a href="#cb30-34" aria-hidden="true" tabindex="-1"></a>  area_sorteio <span class="ot">&lt;-</span> <span class="fu">do.call</span>(rbind, area_sorteio)</span>
<span id="cb30-35"><a href="#cb30-35" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-36"><a href="#cb30-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-37"><a href="#cb30-37" aria-hidden="true" tabindex="-1"></a><span class="co"># checando...</span></span>
<span id="cb30-38"><a href="#cb30-38" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">nrow</span>(area_sorteio) <span class="sc">==</span> <span class="dv">0</span>) {</span>
<span id="cb30-39"><a href="#cb30-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Erro: Nenhuma área de floresta encontrada no município."</span>)</span>
<span id="cb30-40"><a href="#cb30-40" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb30-41"><a href="#cb30-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-42"><a href="#cb30-42" aria-hidden="true" tabindex="-1"></a><span class="co">#visualizando</span></span>
<span id="cb30-43"><a href="#cb30-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-44"><a href="#cb30-44" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb30-45"><a href="#cb30-45" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> r_utm) <span class="sc">+</span></span>
<span id="cb30-46"><a href="#cb30-46" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> legenda<span class="sc">$</span>Cores, <span class="at">na.value =</span> <span class="st">"white"</span>, <span class="at">name =</span> <span class="st">"Uso do Solo"</span>) <span class="sc">+</span></span>
<span id="cb30-47"><a href="#cb30-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-48"><a href="#cb30-48" aria-hidden="true" tabindex="-1"></a>  <span class="co"># limite do município</span></span>
<span id="cb30-49"><a href="#cb30-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector</span>(<span class="at">data =</span> municipio_limite, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb30-50"><a href="#cb30-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-51"><a href="#cb30-51" aria-hidden="true" tabindex="-1"></a>  <span class="co"># área de floresta total</span></span>
<span id="cb30-52"><a href="#cb30-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector</span>(<span class="at">data =</span> floresta, <span class="at">fill =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb30-53"><a href="#cb30-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-54"><a href="#cb30-54" aria-hidden="true" tabindex="-1"></a>  <span class="co"># área de sorteio (floresta dentro do município)</span></span>
<span id="cb30-55"><a href="#cb30-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector</span>(<span class="at">data =</span> area_sorteio, <span class="at">fill =</span> <span class="st">"forestgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb30-56"><a href="#cb30-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-57"><a href="#cb30-57" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Mapa de uso e cobertura do solo em Cabaceiras-PB)"</span>) <span class="sc">+</span></span>
<span id="cb30-58"><a href="#cb30-58" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501200 cells.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercícios_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#sorteio de pontos com distancia minima</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>pontos_finais <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>tentativas <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span>(<span class="fu">is.null</span>(pontos_finais) <span class="sc">||</span> <span class="fu">nrow</span>(pontos_finais) <span class="sc">&lt;</span> <span class="dv">15</span>) {</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  tentativas <span class="ot">&lt;-</span> tentativas <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  cand <span class="ot">&lt;-</span> <span class="fu">spatSample</span>(area_sorteio, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">method =</span> <span class="st">"random"</span>)</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(cand) <span class="sc">&gt;</span> <span class="dv">0</span>) {</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.null</span>(pontos_finais)) {</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>      pontos_finais <span class="ot">&lt;-</span> cand</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>      dists <span class="ot">&lt;-</span> <span class="fu">distance</span>(cand, pontos_finais)</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>      <span class="cf">if</span> (<span class="fu">min</span>(dists) <span class="sc">&gt;=</span> <span class="dv">1000</span>) {</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>        pontos_finais <span class="ot">&lt;-</span> <span class="fu">rbind</span>(pontos_finais, cand)</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>      }</span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (tentativas <span class="sc">&gt;</span> <span class="dv">5000</span>) <span class="cf">break</span></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="co">#buffers e extração da composição da paisagem</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-27"><a href="#cb32-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificar CRS</span></span>
<span id="cb32-28"><a href="#cb32-28" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">identical</span>(<span class="fu">crs</span>(pontos_finais), <span class="fu">crs</span>(r_utm))) {</span>
<span id="cb32-29"><a href="#cb32-29" aria-hidden="true" tabindex="-1"></a>  pontos_finais <span class="ot">&lt;-</span> <span class="fu">project</span>(pontos_finais, <span class="fu">crs</span>(r_utm))</span>
<span id="cb32-30"><a href="#cb32-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb32-31"><a href="#cb32-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-32"><a href="#cb32-32" aria-hidden="true" tabindex="-1"></a>buffers <span class="ot">&lt;-</span> <span class="fu">buffer</span>(pontos_finais, <span class="at">width =</span> <span class="dv">500</span>)</span>
<span id="cb32-33"><a href="#cb32-33" aria-hidden="true" tabindex="-1"></a>buffers<span class="sc">$</span>id_paisagem <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(buffers)</span>
<span id="cb32-34"><a href="#cb32-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-35"><a href="#cb32-35" aria-hidden="true" tabindex="-1"></a><span class="co"># Extração e processamento</span></span>
<span id="cb32-36"><a href="#cb32-36" aria-hidden="true" tabindex="-1"></a>extracao <span class="ot">&lt;-</span> terra<span class="sc">::</span><span class="fu">extract</span>(r_utm, buffers)</span>
<span id="cb32-37"><a href="#cb32-37" aria-hidden="true" tabindex="-1"></a>nome_col_raster <span class="ot">&lt;-</span> <span class="fu">names</span>(extracao)[<span class="dv">2</span>]</span>
<span id="cb32-38"><a href="#cb32-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-39"><a href="#cb32-39" aria-hidden="true" tabindex="-1"></a>tabela_final <span class="ot">&lt;-</span> extracao <span class="sc">%&gt;%</span></span>
<span id="cb32-40"><a href="#cb32-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">id_buffer =</span> ID, <span class="at">categoria_bruta =</span> <span class="sc">!!</span><span class="fu">sym</span>(nome_col_raster)) <span class="sc">%&gt;%</span></span>
<span id="cb32-41"><a href="#cb32-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id_buffer) <span class="sc">%&gt;%</span></span>
<span id="cb32-42"><a href="#cb32-42" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">total_px =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb32-43"><a href="#cb32-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id_buffer, categoria_bruta) <span class="sc">%&gt;%</span></span>
<span id="cb32-44"><a href="#cb32-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb32-45"><a href="#cb32-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">pixels =</span> <span class="fu">n</span>(),</span>
<span id="cb32-46"><a href="#cb32-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">percentagem =</span> (pixels <span class="sc">/</span> <span class="fu">first</span>(total_px)) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb32-47"><a href="#cb32-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb32-48"><a href="#cb32-48" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb32-49"><a href="#cb32-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Categoria_Limpa =</span> <span class="fu">as.character</span>(categoria_bruta)) <span class="sc">%&gt;%</span></span>
<span id="cb32-50"><a href="#cb32-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(legenda <span class="sc">%&gt;%</span> <span class="fu">select</span>(Categoria, Cores), <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"Categoria_Limpa"</span> <span class="ot">=</span> <span class="st">"Categoria"</span>))</span>
<span id="cb32-51"><a href="#cb32-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-52"><a href="#cb32-52" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(tabela_final, <span class="st">"uso_solo_cabaceiras_final.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb32-53"><a href="#cb32-53" aria-hidden="true" tabindex="-1"></a><span class="fu">writeVector</span>(pontos_finais, <span class="st">"pontos_final.shp"</span>, <span class="at">overwrite=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-54"><a href="#cb32-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-55"><a href="#cb32-55" aria-hidden="true" tabindex="-1"></a><span class="fu">writeVector</span>(buffers, <span class="st">"buffers_500m.shp"</span>, <span class="at">overwrite=</span><span class="cn">TRUE</span>)</span>
<span id="cb32-56"><a href="#cb32-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-57"><a href="#cb32-57" aria-hidden="true" tabindex="-1"></a><span class="co">#visualização</span></span>
<span id="cb32-58"><a href="#cb32-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-59"><a href="#cb32-59" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb32-60"><a href="#cb32-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-61"><a href="#cb32-61" aria-hidden="true" tabindex="-1"></a><span class="co"># adicionar ID aos pontos</span></span>
<span id="cb32-62"><a href="#cb32-62" aria-hidden="true" tabindex="-1"></a>pontos_finais<span class="sc">$</span>ID <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(pontos_finais)</span>
<span id="cb32-63"><a href="#cb32-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-64"><a href="#cb32-64" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb32-65"><a href="#cb32-65" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatraster</span>(<span class="at">data =</span> r_utm) <span class="sc">+</span></span>
<span id="cb32-66"><a href="#cb32-66" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> legenda<span class="sc">$</span>Cores, <span class="at">na.value =</span> <span class="st">"white"</span>, <span class="at">name =</span> <span class="st">"Uso do Solo"</span>) <span class="sc">+</span></span>
<span id="cb32-67"><a href="#cb32-67" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector</span>(<span class="at">data =</span> buffers, <span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb32-68"><a href="#cb32-68" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector</span>(<span class="at">data =</span> pontos_finais, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb32-69"><a href="#cb32-69" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_spatvector_text</span>(<span class="at">data =</span> pontos_finais, <span class="fu">aes</span>(<span class="at">label =</span> ID),</span>
<span id="cb32-70"><a href="#cb32-70" aria-hidden="true" tabindex="-1"></a>                       <span class="at">color =</span> <span class="st">"white"</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb32-71"><a href="#cb32-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Pontos amostrais e buffers de 500 m"</span>) <span class="sc">+</span></span>
<span id="cb32-72"><a href="#cb32-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-73"><a href="#cb32-73" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>&lt;SpatRaster&gt; resampled to 501200 cells.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercícios_files/figure-html/unnamed-chunk-1-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co">#analise com landscapemetrics ----------------------------------------</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar o valor numérico da classe Floresta</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>id_floresta <span class="ot">&lt;-</span> legenda<span class="sc">$</span>id[legenda<span class="sc">$</span>Categoria <span class="sc">==</span> <span class="st">"Formação Florestal"</span>]</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Lista para armazenar métricas de cada buffer</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>metricas_lista <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="co"># armazenar as métricas de patch</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>metricas_patch_lista <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(buffers)) {</span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Recortar o raster para o buffer i</span></span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  crop_i <span class="ot">&lt;-</span> <span class="fu">crop</span>(r_utm, buffers[i,])</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  mask_i <span class="ot">&lt;-</span> <span class="fu">mask</span>(crop_i, buffers[i,])</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcular duversidade Shannon diversity</span></span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>  shannon <span class="ot">&lt;-</span> <span class="fu">lsm_l_shdi</span>(mask_i)</span>
<span id="cb34-19"><a href="#cb34-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-20"><a href="#cb34-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcular métricas de classe para todas as classes</span></span>
<span id="cb34-21"><a href="#cb34-21" aria-hidden="true" tabindex="-1"></a>  pland_all <span class="ot">&lt;-</span> <span class="fu">lsm_c_pland</span>(mask_i)</span>
<span id="cb34-22"><a href="#cb34-22" aria-hidden="true" tabindex="-1"></a>  ed_all <span class="ot">&lt;-</span> <span class="fu">lsm_c_ed</span>(mask_i)</span>
<span id="cb34-23"><a href="#cb34-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-24"><a href="#cb34-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-25"><a href="#cb34-25" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Calcula as métricas de patch</span></span>
<span id="cb34-26"><a href="#cb34-26" aria-hidden="true" tabindex="-1"></a>  p_area  <span class="ot">&lt;-</span> <span class="fu">lsm_p_area</span>(mask_i)</span>
<span id="cb34-27"><a href="#cb34-27" aria-hidden="true" tabindex="-1"></a>  p_core  <span class="ot">&lt;-</span> <span class="fu">lsm_p_core</span>(mask_i)</span>
<span id="cb34-28"><a href="#cb34-28" aria-hidden="true" tabindex="-1"></a>  p_perim <span class="ot">&lt;-</span> <span class="fu">lsm_p_perim</span>(mask_i)</span>
<span id="cb34-29"><a href="#cb34-29" aria-hidden="true" tabindex="-1"></a>  p_shape <span class="ot">&lt;-</span> <span class="fu">lsm_p_shape</span>(mask_i)</span>
<span id="cb34-30"><a href="#cb34-30" aria-hidden="true" tabindex="-1"></a>  p_frac  <span class="ot">&lt;-</span> <span class="fu">lsm_p_frac</span>(mask_i)</span>
<span id="cb34-31"><a href="#cb34-31" aria-hidden="true" tabindex="-1"></a>  p_enn   <span class="ot">&lt;-</span> <span class="fu">lsm_p_enn</span>(mask_i)</span>
<span id="cb34-32"><a href="#cb34-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-33"><a href="#cb34-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Combina todas as métricas de patch do buffer</span></span>
<span id="cb34-34"><a href="#cb34-34" aria-hidden="true" tabindex="-1"></a>  patch_all <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(p_area, p_core, p_perim, p_shape, p_frac, p_enn)</span>
<span id="cb34-35"><a href="#cb34-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-36"><a href="#cb34-36" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtrando apenas para a classe floresta e adicionando o id do buffer</span></span>
<span id="cb34-37"><a href="#cb34-37" aria-hidden="true" tabindex="-1"></a>  patch_floresta <span class="ot">&lt;-</span> patch_all <span class="sc">%&gt;%</span></span>
<span id="cb34-38"><a href="#cb34-38" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(class <span class="sc">==</span> id_floresta) <span class="sc">%&gt;%</span></span>
<span id="cb34-39"><a href="#cb34-39" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">id_buffer =</span> i)</span>
<span id="cb34-40"><a href="#cb34-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-41"><a href="#cb34-41" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Guardando na nova lista</span></span>
<span id="cb34-42"><a href="#cb34-42" aria-hidden="true" tabindex="-1"></a>  metricas_patch_lista[[i]] <span class="ot">&lt;-</span> patch_floresta</span>
<span id="cb34-43"><a href="#cb34-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-44"><a href="#cb34-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-45"><a href="#cb34-45" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filtrar apenas a classe floresta</span></span>
<span id="cb34-46"><a href="#cb34-46" aria-hidden="true" tabindex="-1"></a>  pland_floresta <span class="ot">&lt;-</span> pland_all <span class="sc">%&gt;%</span> <span class="fu">filter</span>(class <span class="sc">==</span> id_floresta)</span>
<span id="cb34-47"><a href="#cb34-47" aria-hidden="true" tabindex="-1"></a>  ed_floresta <span class="ot">&lt;-</span> ed_all <span class="sc">%&gt;%</span> <span class="fu">filter</span>(class <span class="sc">==</span> id_floresta)</span>
<span id="cb34-48"><a href="#cb34-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-49"><a href="#cb34-49" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Extrair valores (se não houver floresta, colocar NA ou 0)</span></span>
<span id="cb34-50"><a href="#cb34-50" aria-hidden="true" tabindex="-1"></a>  div_shannon <span class="ot">&lt;-</span> shannon<span class="sc">$</span>value</span>
<span id="cb34-51"><a href="#cb34-51" aria-hidden="true" tabindex="-1"></a>  perc_floresta <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nrow</span>(pland_floresta) <span class="sc">&gt;</span> <span class="dv">0</span>, pland_floresta<span class="sc">$</span>value, <span class="dv">0</span>)</span>
<span id="cb34-52"><a href="#cb34-52" aria-hidden="true" tabindex="-1"></a>  dens_borda <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">nrow</span>(ed_floresta) <span class="sc">&gt;</span> <span class="dv">0</span>, ed_floresta<span class="sc">$</span>value, <span class="cn">NA</span>)</span>
<span id="cb34-53"><a href="#cb34-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-54"><a href="#cb34-54" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Guardar</span></span>
<span id="cb34-55"><a href="#cb34-55" aria-hidden="true" tabindex="-1"></a>  metricas_lista[[i]] <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb34-56"><a href="#cb34-56" aria-hidden="true" tabindex="-1"></a>    <span class="at">id_buffer =</span> i,</span>
<span id="cb34-57"><a href="#cb34-57" aria-hidden="true" tabindex="-1"></a>    <span class="at">diversidade_shannon =</span> div_shannon,</span>
<span id="cb34-58"><a href="#cb34-58" aria-hidden="true" tabindex="-1"></a>    <span class="at">perc_floresta =</span> perc_floresta,</span>
<span id="cb34-59"><a href="#cb34-59" aria-hidden="true" tabindex="-1"></a>    <span class="at">densidade_borda_m_ha =</span> dens_borda</span>
<span id="cb34-60"><a href="#cb34-60" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb34-61"><a href="#cb34-61" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb34-62"><a href="#cb34-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-63"><a href="#cb34-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinar tudo</span></span>
<span id="cb34-64"><a href="#cb34-64" aria-hidden="true" tabindex="-1"></a>metricas_paisagem <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(metricas_lista)</span>
<span id="cb34-65"><a href="#cb34-65" aria-hidden="true" tabindex="-1"></a>metricas_patch <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(metricas_patch_lista) <span class="co"># Combina a nova rodada</span></span>
<span id="cb34-66"><a href="#cb34-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-67"><a href="#cb34-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Transformar a tabela de manchas no formato do professor (1 linha por buffer)</span></span>
<span id="cb34-68"><a href="#cb34-68" aria-hidden="true" tabindex="-1"></a>tabela_patch <span class="ot">&lt;-</span> metricas_patch <span class="sc">%&gt;%</span></span>
<span id="cb34-69"><a href="#cb34-69" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Agrupa pelo buffer e pela métrica</span></span>
<span id="cb34-70"><a href="#cb34-70" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id_buffer, metric) <span class="sc">%&gt;%</span></span>
<span id="cb34-71"><a href="#cb34-71" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Tira a média dos valores das manchas para cada métrica dentro do buffer</span></span>
<span id="cb34-72"><a href="#cb34-72" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">value =</span> <span class="fu">mean</span>(value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-73"><a href="#cb34-73" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Transforma as linhas das métricas em colunas</span></span>
<span id="cb34-74"><a href="#cb34-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> metric, <span class="at">values_from =</span> value) <span class="sc">%&gt;%</span></span>
<span id="cb34-75"><a href="#cb34-75" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Renomeia id_buffer para plot_id para ficar idêntico ao exemplo</span></span>
<span id="cb34-76"><a href="#cb34-76" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">plot_id =</span> id_buffer)</span>
<span id="cb34-77"><a href="#cb34-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-78"><a href="#cb34-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar como ficou</span></span>
<span id="cb34-79"><a href="#cb34-79" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(tabela_patch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 7
   plot_id  area   core   enn  frac perim shape
     &lt;int&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1       1 1.51  0.0888 107.   1.12  924.  1.83
 2       2 1.40  0.244  143.   1.10  790.  1.68
 3       3 0.444 0      NaN    1.03  298.  1.12
 4       4 4.84  2.18   246.   1.11 1520.  1.81
 5       5 2.31  1.19   115.   1.06  751.  1.43
 6       6 1.60  0.178   89.4  1.14  983.  1.94
 7       7 1.15  0.178  NaN    1.07  596.  1.39
 8       8 2.22  0.0888 NaN    1.16 1311.  2.20
 9       9 3.28  0.977  NaN    1.15 1609.  2.22
10      10 0.222 0      364.   1.07  268.  1.38
11      11 1.78  0.533  NaN    1.02  596.  1.12
12      12 1.07  0.0888 NaN    1.08  596.  1.44
13      13 0.444 0      NaN    1.03  298.  1.12
14      14 0.444 0      233.   1.14  507.  1.86
15      15 0.400 0      215.   1.04  298.  1.19</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(metricas_paisagem)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id_buffer diversidade_shannon perc_floresta densidade_borda_m_ha
1          1          1.23057611     3.6286019            22.206778
2          2          1.43889928     6.7235859            37.608253
3          3          1.28042224     0.5393743             3.620376
4          4          0.98333430    11.7583603            36.203763
5          5          1.33698655    18.2584270            48.078801
6          6          1.32890281     3.8379531            23.614271
7          7          1.25104207     1.3874066             7.163477
8          8          0.79134328     2.6539278            15.675999
9          9          0.62975187     4.0000000            19.592302
10        10          0.17227395     1.0245902            11.003570
11        11          1.12990123     2.1668472             7.272132
12        12          0.75669105     2.1164021             6.510931
13        13          1.11726105     0.5319149             3.570307
14        14          1.13870407     1.0660981            12.164928
15        15          0.08304324     1.6245487            10.904260</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(metricas_paisagem, <span class="st">"metricas_landscapemetrics.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(metricas_patch, <span class="st">"metricas_patch_landscapemetrics.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co">#painel de paisagens</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>lista_recortes <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(buffers)) {</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  crop_i <span class="ot">&lt;-</span> <span class="fu">crop</span>(r_utm, buffers[i, ])</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  mask_i <span class="ot">&lt;-</span> <span class="fu">mask</span>(crop_i, buffers[i, ])</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  df_i <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(mask_i, <span class="at">xy =</span> <span class="cn">TRUE</span>, <span class="at">cells =</span> <span class="cn">TRUE</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  df_i<span class="sc">$</span>id_buffer <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="st">"Paisagem"</span>, i)</span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>  lista_recortes[[i]] <span class="ot">&lt;-</span> df_i</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>df_painel <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(lista_recortes)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_painel) <span class="sc">+</span></span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> Categoria)) <span class="sc">+</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">setNames</span>(legenda<span class="sc">$</span>Cores, legenda<span class="sc">$</span>Categoria)) <span class="sc">+</span></span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>id_buffer, <span class="at">nrow =</span> <span class="dv">3</span>, <span class="at">ncol =</span> <span class="dv">5</span>, <span class="at">scales =</span> <span class="st">"free"</span>) <span class="sc">+</span></span>
<span id="cb38-22"><a href="#cb38-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-23"><a href="#cb38-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Painel de Amostragem: 15 Paisagens de Cabaceiras - PB"</span>,</span>
<span id="cb38-24"><a href="#cb38-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Recortes circulares de 500m de raio (Interior de Floresta)"</span>,</span>
<span id="cb38-25"><a href="#cb38-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Uso do Solo"</span>) <span class="sc">+</span></span>
<span id="cb38-26"><a href="#cb38-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb38-27"><a href="#cb38-27" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb38-28"><a href="#cb38-28" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb38-29"><a href="#cb38-29" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercícios_files/figure-html/unnamed-chunk-1-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Visulaizando somente a paisagem 5</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>df_5 <span class="ot">&lt;-</span> df_painel <span class="sc">%&gt;%</span> <span class="fu">filter</span>(id_buffer <span class="sc">==</span> <span class="st">"Paisagem 5"</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_5) <span class="sc">+</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> Categoria)) <span class="sc">+</span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">setNames</span>(legenda<span class="sc">$</span>Cores, legenda<span class="sc">$</span>Categoria)) <span class="sc">+</span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Detalhe da Paisagem 5"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Uso do Solo"</span>) <span class="sc">+</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercícios_files/figure-html/unnamed-chunk-1-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Visualizando somente a paisagem 4</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>df_4 <span class="ot">&lt;-</span> df_painel <span class="sc">%&gt;%</span> <span class="fu">filter</span>(id_buffer <span class="sc">==</span> <span class="st">"Paisagem 4"</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_4) <span class="sc">+</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> Categoria)) <span class="sc">+</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">setNames</span>(legenda<span class="sc">$</span>Cores, legenda<span class="sc">$</span>Categoria)) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Detalhe da Paisagem 4"</span>,</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Uso do Solo"</span>) <span class="sc">+</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.ticks =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">panel.grid =</span> <span class="fu">element_blank</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Exercícios_files/figure-html/unnamed-chunk-1-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>